local mod = assert(nokore_world_standard)

mod:require("nodes/andesite.lua")
mod:require("nodes/granite.lua")
mod:require("nodes/diorite.lua")
mod:require("nodes/dirt.lua")
mod:require("nodes/grass.lua")
mod:require("nodes/stone.lua")
mod:require("nodes/cobblestone.lua")
mod:require("nodes/sand.lua")
mod:require("nodes/sandstone.lua")
mod:require("nodes/gravel.lua")
